# .goreleaser.yaml
project_name: gaia
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    main: ./
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -extldflags '-static'
      - -s -w
      - -X gaia/commands.version={{.Version}}
      - -X gaia/commands.commitSHA={{.FullCommit}}
      - -X gaia/commands.buildDate={{.Date}}
brews:
  - name: "gaia"
    homepage: "https://github.com/vonglasow/gaia"
    description: "Cli tool to ask local LLM with ollama"
    license: "GPL3"
    url_template: "https://github.com/vonglasow/{{ .ProjectName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    repository:
      owner: vonglasow
      name: homebrew-tap
      branch: main
