---
queue_rules:
  - name: dependabot-dev-queue
    autoqueue: true
    merge_method: rebase
    merge_conditions:
      - check-success = lint
      - check-success = test
      - -conflict

pull_request_rules:
  - name: Auto-merge Dependabot PRs to dev
    conditions:
      - author = dependabot[bot]
      - base = dev
      - check-success = lint
      - check-success = test
      - -draft
    actions:
      queue:
        name: dependabot-dev-queue
