pull_request_rules:
  - name: Automatic merge for Dependabot PRs
    conditions:
      - author = dependabot[bot]
      - check-success = lint
      - check-success = test
    actions:
      merge:
        method: rebase
        queue:
          name: auto
